version: 2
jobs:
  build:
    docker:
      - image: ishikocpp/gcc-boost:9.1.0-1.70.0
    steps:
      - run: 
          name: "Set ISHIKO environment variable and create directory"
          command: mkdir /Ishiko && echo 'export ISHIKO="/Ishiko"' >> $BASH_ENV
      - checkout:
          path: /Ishiko/TestFramework
      - run:
          name: "Checkout Ishiko/Process dependency"
          command: cd /Ishiko && git clone https://github.com/Ishiko-Cpp/Process.git
      - run:
          name: Build
          command: cd Core/Makefiles/GNUmakefile && make
      - run:
          name: Test build
          command: cd Tests/Core/Makefiles/GNUmakefile && make
