version: 2
jobs:
  build:
    docker:
      - image: ishikocpp/gcc-boost:9.1.0-1.70.0
    steps:
      - run: 
          name: "Set ISHIKO_CPP environment variable and create directory"
          command: mkdir /Ishiko-cpp && echo 'export ISHIKO_CPP="/Ishiko-cpp"' >> $BASH_ENV
      - run:
          name: "Checkout Ishiko-cpp/Errors dependency"
          command: cd /Ishiko-cpp && git clone https://github.com/Ishiko-cpp/Errors.git
      - run:
          name: "Checkout Ishiko-cpp/Process dependency"
          command: cd /Ishiko-cpp && git clone https://github.com/Ishiko-cpp/Process.git
      - checkout:
          path: /Ishiko-cpp/TestFramework
      - run:
          name: "Build Ishiko-cpp/Errors dependency"
          command: cd /Ishiko-cpp/Errors/Makefiles/GNUmakefile && make
      - run:
          name: "Build Ishiko-cpp/Process dependency"
          command: cd /Ishiko-cpp/Process/Makefiles/GNUmakefile && make
      - run:
          name: Build
          command: cd /Ishiko-cpp/TestFramework/Core/Makefiles/GNUmakefile && make
      - run:
          name: Test build
          command: cd /Ishiko-cpp/TestFramework/Tests/Core/Makefiles/GNUmakefile && make
      - run:
          name: Build WriteFileTestHelper
          command: cd /Ishiko-cpp/TestFramework/Tests/Core/WriteFileTestHelper/Makefiles/GNUmakefile && make
      - run:
          name: Run the tests
          command: cd /Ishiko-cpp/TestFramework/Tests/Core/Makefiles/GNUmakefile && ./IshikoTestFrameworkCoreTests
